title: Side Project Checklist
email: marketing@portablecto.com
author: Karl Hughes
description: > # this means to ignore newlines until "baseurl:"
  A comprehensive, chronologically ordered checklist of marketing tactics and ideas you can try with
  your next side project.
baseurl: "/"
url: "https://www.sideprojectchecklist.com"

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
google_analytics: UA-19700764-11
gems:
  - jekyll-archives
  - jekyll-sitemap

permalink: /:year/:title/
paginate_path: /blog/:num/
paginate: 5
comments: false

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/
